- name: Ensure Apache RHEL SCL repo is installed
  package:
    name: centos-release-scl
    state: "{{ apache_packages_state }}"
  when: "{{ apache_redhat_use_scl_packages }} == true"

- name: Ensure Apache is installed on RHEL.
  package:
    name: "{{ apache_packages }}"
    state: "{{ apache_packages_state }}"
    enablerepo: "{{ apache_enablerepo | default(omit, true) }}"
